### ISSUE TITLE
Could not interpret optimizer identifier

### ISSUE THREAD

**Issue by HenningLilienkamp** [CyberZHG/keras-gradient-accumulation#6]
Hi guys,
I am running keras-gradient-accumulation 0.0.6 with Keras 2.3.0 and Tensorflow 2.0.0 on Ubuntu 18.04. I am getting the following error message:

Traceback (most recent call last):
  File "cnnlib/Unet_training.py", line 46, in <module>
    model, name = build_Unet_Vanilla(loss_function=none_zero_MSE)
  File "/home/lilienka/Documents/CNGMM_full/cngmm_new/cnnlib/architectures.py", line 415, in build_Unet_Vanilla
    model.compile(optimizer=optimizer, loss=loss_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 251, in compile
    self._set_optimizer(optimizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1454, in _set_optimizer
    self.optimizer = optimizers.get(optimizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/optimizers.py", line 850, in get
    raise ValueError('Could not interpret optimizer identifier:', identifier)
ValueError: ('Could not interpret optimizer identifier:', <keras_gradient_accumulation.optimizer_v1.AdamAccumulated object at 0x7f776c4a9358>)

Do you have any suggestions?
Thanks!

**Comment by denis-dmitriev** [comment]
I got the same issue and for now have no idea how to resolve it. Do you have any suggestions?

Thanks!


Traceback (most recent call last):
  File "EMF/Models/EfficientDet/main.py", line 1374, in <module>
    main(args_dict=args)
  File "EMF/Models/EfficientDet/main.py", line 1037, in main
    'classification': focal(),},)
  File "/home/everestlabs/anaconda3/envs/yolo3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/everestlabs/anaconda3/envs/yolo3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 252, in compile
    self._set_optimizer(optimizer)
  File "/home/everestlabs/anaconda3/envs/yolo3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1453, in _set_optimizer
    self.optimizer = optimizers.get(optimizer)
  File "/home/everestlabs/anaconda3/envs/yolo3/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizers.py", line 848, in get
    raise ValueError('Could not interpret optimizer identifier:', identifier)
ValueError: ('Could not interpret optimizer identifier:', <keras_gradient_accumulation.optimizers.GradientAccumulation object at 0x7f350479db50>)
